name: Build, Sign, Deploy - Keycloak

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HARBOR_REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install and Verify CA Certificate
        run: |
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}
          echo "${{ secrets.HARBOR_CA_CRT }}" | sudo tee /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}/ca.crt > /dev/null
          sudo cp /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}/ca.crt /usr/local/share/ca-certificates/harbor-ca.crt
          sudo update-ca-certificates
          sudo systemctl restart docker
          sudo ls -l /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.PROJECT_NAME }}-${{ github.ref_name }}/${{ github.event.repository.name }}:24.0.4 .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.PROJECT_NAME }}-${{ github.ref_name }}/${{ github.event.repository.name }}:24.0.4

  sign:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Cosign and CA Certificate
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v1.4.1/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}
          echo "${{ secrets.HARBOR_CA_CRT }}" | sudo tee /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}/ca.crt > /dev/null
          sudo cp /etc/docker/certs.d/${{ secrets.HARBOR_REGISTRY }}/ca.crt /usr/local/share/ca-certificates/harbor-ca.crt
          sudo update-ca-certificates
          sudo systemctl restart docker

      - name: Prepare Cosign Key
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key

      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.PROJECT_NAME }}-${{ github.ref_name }}/${{ github.event.repository.name }}:24.0.4

  deploy:
    needs: sign
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.DEPLOYER_SSH_KEY }}" > deployer_key
          chmod 600 deployer_key

      - name: Rollout Restart StatefulSet
        run: |
          ssh -o StrictHostKeyChecking=no -i deployer_key ${{ secrets.DEPLOYER_USERNAME }}@${{ secrets.SERVER_HOST }} 'kubectl rollout restart statefulset ${{ github.event.repository.name }} -n ${{ secrets.PROJECT_NAME }}-sso'
